#!/usr/bin/env bash
# Is the tracked record of the candidate images still a description of the files on disk?
#
# Why this exists
# ---------------
# Every offline reading this project now depends on is keyed by a PATH. `zl1-modem-mount.sh` reads
# two candidate images and a rootfs image; the probes name images; `flash-boot-image.sh` refuses an
# image that is not hash-verified against `SHA256SUMS`. The one thing none of them could answer was:
#
#     is the file at that path still the file the record says it is?
#
# That is not a theoretical worry here. Images get REBUILT UNDER THE SAME FILENAME -- the image this
# project boots, `halium-boot-zl1-v63-rebuilt.img`, IS a rebuild that kept v63's name. `manifests/
# halium-boot-candidates.md` is regenerated BY HAND (`scripts/gen-candidate-manifest.sh`), and the
# images live outside this repo, so a rebuild that nobody re-manifested leaves every document that
# cites that hash describing a file that no longer exists anywhere -- and every offline instrument
# silently reading a different one.
#
# This is the same defect class the project keeps finding in its harnesses ("a fixture landed in the
# tree it tests", "a check reading HEAD self-compares once the fix lands"), one level up: a reading is
# only as good as the identity of the file it read.
#
# What it does, all read-only and all host-side
# ---------------------------------------------
#   1. the record      -- the manifest: does it exist, does it parse, how many rows
#   2. the comparison  -- per file: present? same size? same sha256?
#   3. the other way   -- a *.img in the directory that the record does NOT have. This is the state
#                         that produces a mis-attributed reading: the file is real, the record is
#                         silent, and nothing else in the tree would notice.
#   4. SHA256SUMS      -- the second record, generated alongside and used by flash-boot-image.sh.
#                         Two records can disagree, and a guard that checked one would be reading
#                         half of the evidence.
#   5. the verdict     -- IN SYNC / DRIFTED / <nothing to compare>
#
# The comparison EXCLUDES the manifest's `Generated by ... on <timestamp>` line, and that is not a
# detail: that line is designed to change on every regeneration, so a byte-comparison against it would
# fail every single run. A check that always fails is a check nobody reads, and this project has
# written that down before (docs 149: an assertion that can never match is worse than a failing one).
# What is compared is the thing the file is FOR -- the table of filename -> bytes -> sha256.
#
# --quick compares SIZE ONLY and says so in its own verdict, because a same-size edit is invisible to
# it and a reading that does not state its weakness is indistinguishable from a strong one.
#
# Usage: zl1-artifact-manifest.sh [--manifest FILE] [--dir DIR] [--quick] [--quiet]
#   --manifest FILE   the tracked record (default: manifests/halium-boot-candidates.md in this repo)
#   --dir DIR         the image directory (default: /mnt/data/halium-zl1-candidates)
#   --quick           compare sizes only -- refuse to hash (and say what that cannot see)
#   --quiet           print the verdict only
#
# Exit codes: 0 in sync; 1 the record and the disk disagree; 2 a tool or an input is missing;
#             3 the record could not be read -- NOTHING is claimed (and NOT a pass).
#
# What this NEVER does: write, create, delete, hash-to-a-file, or touch the device. It opens images
# READ-ONLY and it does not have a device code path at all.

set -uo pipefail
export LC_ALL=C

HERE=$(cd -- "$(dirname -- "$0")" && pwd)
REPO=$(cd -- "$HERE/../.." && pwd)
MANIFEST="${ZL1_CANDIDATE_MANIFEST:-$REPO/manifests/halium-boot-candidates.md}"
DIR="${ZL1_CANDIDATE_DIR:-/mnt/data/halium-zl1-candidates}"
QUICK=0
QUIET=0

while [ $# -gt 0 ]; do
  case "$1" in
  --manifest) MANIFEST="${2?--manifest needs a path}"; shift 2 ;;
  --dir) DIR="${2?--dir needs a path}"; shift 2 ;;
  --quick) QUICK=1; shift ;;
  --quiet) QUIET=1; shift ;;
  --help|-h) awk 'NR==1{next} /^#/{print; next} {exit}' "$0"; exit 0 ;;
  *) echo "unknown argument: $1 (try --help)" >&2; exit 2 ;;
  esac
done

say() { [ "$QUIET" = 1 ] && [ -n "${1:-}" ] && return 0; printf '%s\n' "$*"; }
bad() { printf 'REFUSED: %s\n' "$*" >&2; }

for t in sha256sum awk stat sort; do
  command -v "$t" >/dev/null 2>&1 || { bad "no $t(1) on this host -- this is a HOST problem, not a reading about the record."; exit 2; }
done
[ -r "$MANIFEST" ] || { bad "cannot read the record: $MANIFEST"; exit 2; }
[ -d "$DIR" ] || { bad "cannot read the image directory: $DIR"; echo "         With no directory there is nothing to compare against, and 'I could not look'" >&2; echo "         must not be printed as 'it agrees'." >&2; exit 2; }

say "zl1 artifact manifest -- is the record still a description of the disk?"
say "  READ-ONLY, HOST-SIDE, NO DEVICE: images are opened for hashing only."
say "  record:    $MANIFEST"
say "  directory: $DIR"
say

# ==================================================================================================
say "== 1. the record itself =="
# ==================================================================================================
ROWS=$(awk '/^\| `/{n++} END{print n+0}' "$MANIFEST")
GENON=$(sed -n 's/^Generated by .* on \(.*\)\.$/\1/p' "$MANIFEST" | sed -n '1p')
say "  rows in the table: $ROWS"
say "  the record says it was generated on: ${GENON:-?}"
if [ "$ROWS" -eq 0 ]; then
  say
  say "== verdict: UNREADABLE"
  say "   The record carries NO table rows. Either this is not the manifest, or its table shape"
  say "   changed and this parser no longer matches it. Either way NOTHING is claimed here -- and"
  say "   note what the tempting alternative would have been: with zero rows to compare, a checker"
  say "   that reported 'no drift found' would be reporting a pass on an empty set. docs 148 calls"
  say "   that shape out by name (a report that cannot print its gaps reads exactly like one with none)."
  exit 3
fi
say "  (the 'generated on' line is NOT compared -- see the header: it changes by design, and a"
say "   comparison that includes it fails on every run. What is compared is the TABLE.)"
say

# ==================================================================================================
say "== 2. every row, against the file it names =="
# ==================================================================================================
# One sha256sum invocation for the whole directory rather than one per file: the I/O is the same and
# this keeps the runtime dominated by the 4 GB system image instead of by process starts.
SUMS=""
if [ "$QUICK" = 0 ]; then
  SUMS=$(cd "$DIR" && sha256sum -- *.img 2>/dev/null)
fi
sha_of() { printf '%s\n' "$SUMS" | awk -v f="$1" '$2 == f || $2 == "*"f {print $1; exit}'; }

OK=0; DRIFT=0; MISSING=0; UNPARSED=0
while IFS= read -r line; do
  case "$line" in '| `'*) ;; *) continue ;; esac
  name=$(printf '%s' "$line" | sed -n 's/^| `\([^`]*\)` |.*/\1/p')
  size=$(printf '%s' "$line" | sed -n 's/^| `[^`]*` | \([0-9][0-9]*\) |.*/\1/p')
  sha=$(printf '%s' "$line" | sed -n 's/^| `[^`]*` | [0-9][0-9]* | `\([0-9a-fA-F]*\)` |.*/\1/p')
  if [ -z "$name" ] || [ -z "$size" ] || [ -z "$sha" ]; then
    UNPARSED=$((UNPARSED + 1))
    say "  ** the record has a row this parser cannot read, and it will NOT be counted as checked:"
    say "     $line"
    continue
  fi
  f="$DIR/$name"
  if [ ! -e "$f" ]; then
    MISSING=$((MISSING + 1))
    say "  MISSING   $name -- the record has it, the directory does not"
    continue
  fi
  asize=$(stat -c %s "$f" 2>/dev/null)
  if [ -z "$asize" ]; then
    MISSING=$((MISSING + 1))
    say "  UNREADABLE $name -- present, but its size could not be read"
    continue
  fi
  if [ "$asize" != "$size" ]; then
    DRIFT=$((DRIFT + 1))
    say "  DRIFTED   $name -- size: record $size, disk $asize"
    continue
  fi
  if [ "$QUICK" = 1 ]; then
    OK=$((OK + 1))
    continue
  fi
  asha=$(sha_of "$name")
  if [ -z "$asha" ]; then
    DRIFT=$((DRIFT + 1))
    say "  UNREADABLE $name -- size matches, but sha256sum produced nothing for it"
    continue
  fi
  if [ "$asha" != "$sha" ]; then
    DRIFT=$((DRIFT + 1))
    say "  DRIFTED   $name -- sha256:"
    say "              record $sha"
    say "              disk   $asha"
    say "              (same filename, same size, different bytes: this is what a REBUILD UNDER THE"
    say "               SAME NAME looks like, and it is the case a size-only comparison cannot see)"
    continue
  fi
  OK=$((OK + 1))
done < "$MANIFEST"
if [ "$QUICK" = 1 ]; then
  say "  verified by SIZE ONLY: $OK rows"
  say "  (--quick; a same-size edit is invisible to this run, so its verdict is weaker than the default)"
else
  say "  verified by size AND sha256: $OK rows"
fi
say "  drifted: $DRIFT   missing: $MISSING   unreadable rows: $UNPARSED"
say

# ==================================================================================================
say "== 3. the other direction: an image the record does not have =="
# ==================================================================================================
# A file the record is SILENT about is exactly how a reading gets attributed to the wrong image: the
# file is real, the offline instrument that defaults to a path picks it up, and no document disagrees.
EXTRA=0
for f in "$DIR"/*.img; do
  [ -e "$f" ] || continue
  b=$(basename -- "$f")
  if ! grep -qF -- "| \`$b\` |" "$MANIFEST"; then
    EXTRA=$((EXTRA + 1))
    say "  EXTRA     $b ($(stat -c %s "$f") bytes) -- on disk, not in the record"
  fi
done
if [ "$EXTRA" -eq 0 ]; then
  say "  (no .img on disk is missing from the record)"
else
  say "  ^ a file here is real and the record is silent about it. Regenerate the manifest rather than"
  say "    trusting a reading that names it."
fi
say

# ==================================================================================================
say "== 4. the second record: SHA256SUMS =="
# ==================================================================================================
# `gen-candidate-manifest.sh` writes this alongside the images and `flash-boot-image.sh` refuses an
# image that is not verified against it. Two records of the same thing can disagree, so a guard that
# read only one would be reading half of the evidence.
SUMSFILE="$DIR/SHA256SUMS"
SUMDRIFT=0
if [ ! -r "$SUMSFILE" ]; then
  say "  (no SHA256SUMS in the directory -- NOT a failure, and NOT checked: it is written alongside"
  say "   the manifest, so its absence means this directory was not produced by the generator or was"
  say "   cleaned. Reported rather than demanded, and deliberately not counted as a pass.)"
elif [ "$QUICK" = 1 ]; then
  say "  (--quick: SHA256SUMS is a hash list, so there is nothing weaker to compare it with -- skipped,"
  say "   said out loud rather than silently.)"
else
  n=$(command grep -c '^[0-9a-f]\{64\}  ' "$SUMSFILE" 2>/dev/null || true)
  say "  entries in it: ${n:-0}"
  while IFS= read -r ln; do
    case "$ln" in [0-9a-f]*) ;; *) continue ;; esac
    s=$(printf '%s' "$ln" | awk '{print $1}')
    b=$(printf '%s' "$ln" | sed 's/^[0-9a-f]*  //')
    m=$(grep -F -- "| \`$b\` |" "$MANIFEST" | sed -n "s/^| \`[^\`]*\` | [0-9][0-9]* | \`\([0-9a-fA-F]*\)\` |.*/\1/p" | sed -n '1p')
    if [ -z "$m" ]; then
      SUMDRIFT=$((SUMDRIFT + 1))
      say "  ONLY HERE  $b is in SHA256SUMS and NOT in the record -- the two records disagree about what exists"
      continue
    fi
    if [ "$s" != "$m" ]; then
      SUMDRIFT=$((SUMDRIFT + 1))
      say "  DISAGREE   $b -- the two records give different hashes for the same name:"
      say "              manifest   $m"
      say "              SHA256SUMS $s"
    fi
  done < "$SUMSFILE"
  if [ "$SUMDRIFT" -eq 0 ]; then
    say "  (the two records agree on every name they share)"
  fi
fi
say

# ==================================================================================================
say "== 5. the verdict =="
# ==================================================================================================
say
if [ "$DRIFT" -gt 0 ] || [ "$MISSING" -gt 0 ] || [ "$EXTRA" -gt 0 ] || [ "$UNPARSED" -gt 0 ] || [ "$SUMDRIFT" -gt 0 ]; then
  say "== verdict: DRIFTED"
  say "   $DRIFT drifted, $MISSING missing, $EXTRA on disk but not in the record, $UNPARSED rows this"
  say "   parser could not read, $SUMDRIFT disagreement(s) between the two records."
  say
  say "   What this means, stated as narrowly as it goes: the tracked record is NOT a description of"
  say "   this directory any more. It does NOT mean any image is corrupt or unusable -- a rebuild is a"
  say "   legitimate thing to do. It means every document and every offline instrument that names one"
  say "   of these files BY PATH is now reading something the record does not describe, and the fix is"
  say "   to say which build it is:"
  say
  say "     bash scripts/gen-candidate-manifest.sh        # regenerate the record from the disk"
  say
  say "   and then re-read whatever cited a hash, because a hash that was right about the OLD file is"
  say "   now a statement about a file that may not exist anywhere."
  exit 1
fi
if [ "$QUICK" = 1 ]; then
  say "== verdict: IN SYNC (SIZES ONLY)"
  say "   Every row's SIZE matches and no file is unaccounted for. This run did NOT hash anything, so"
  say "   it cannot see an edit that kept the size -- which is precisely the shape of an in-place"
  say "   rebuild. The default run can; this one says out loud which one it is."
  exit 0
fi
say "== verdict: IN SYNC"
say "   Every row matches in size AND sha256, no file on disk is missing from the record, and the two"
say "   records agree. The offline readings drawn from this directory are readings of the files the"
say "   record describes."
exit 0
