#!/bin/sh
# zl1 artifact manifest, offline -- self-test.
#
# Host-side, no device, and it cannot have one: the subject reads a TEXT FILE and a DIRECTORY OF IMAGES.
# So the fixtures are a real record and real image files, and every interesting case is made by
# MUTATING the disk under a record that was correct a moment ago -- because that is exactly the event
# the subject exists to notice (an image rebuilt in place, a file removed, a new build nobody declared).
#
# What is under test:
#
#   1. IT IS A COMPARISON, NOT A RITUAL. An IN SYNC run over a fixture built from the directory proves
#      nothing by itself, so each mutation below changes ONE thing about the disk and requires the
#      verdict to move -- and to NAME what moved.
#   2. THE EXCLUSION THAT MAKES IT USABLE. The record carries a `Generated by ... on <timestamp>` line
#      that changes every time it is regenerated by design. A comparison that included it would fail on
#      every single run, and a check that always fails is a check nobody reads (docs 149). The fixture
#      carries a DIFFERENT timestamp from the record and must still be IN SYNC.
#   3. --quick IS WEAKER AND SAYS SO. A same-size edit is invisible to a size-only run. That is not a
#      footnote: it is asserted, by running BOTH modes over the SAME same-size mutation and requiring
#      them to disagree. If they ever agree, one of the two is not doing what it claims.
#   4. A ROW IT CANNOT READ IS NOT A ROW IT CHECKED. A malformed row must be counted and reported, and
#      an EMPTY table must reach UNREADABLE -- because "I compared nothing and found nothing" printed
#      as a pass is the shape this whole project keeps finding (docs 148).
#   5. IT WROTE NOTHING. Static, over the shipped file: the subject opens images for hashing and that is
#      all. It has no device code path at all.
#
# Usage: zl1-artifact-manifest-selftest.sh [--keep]
#
# Exit codes: 0 every scenario behaved; 1 something did not; 2 the harness could not set up.

set -u

KEEP=0
while [ $# -gt 0 ]; do
  case "$1" in
  --keep) KEEP=1; shift ;;
  --help|-h) awk 'NR==1{next} /^#/{print; next} {exit}' "$0" ; exit 0 ;;
  *) echo "unknown argument: $1 (try --help)" >&2; exit 2 ;;
  esac
done

HERE=$(dirname "$0")
SRC="$HERE/zl1-artifact-manifest.sh"
[ -r "$SRC" ] || { echo "cannot read $SRC" >&2; exit 2; }
for t in sha256sum stat awk sort; do
  command -v "$t" >/dev/null 2>&1 || { echo "this harness needs $t" >&2; exit 2; }
done

W=${TMPDIR:-/tmp}/zl1-artifact-manifest-selftest
rm -rf "$W"
mkdir -p "$W" || exit 2
BASH_BIN=$(command -v bash) || exit 2

PASS=0; FAIL=0; SKIP=0
ok()   { PASS=$(( PASS + 1 )); printf 'PASS  %s\n' "$1"; }
bad()  { FAIL=$(( FAIL + 1 )); printf 'FAIL  %s\n' "$1"; }
skip() { SKIP=$(( SKIP + 1 )); printf 'SKIP  %s\n' "$1"; }
want()   { if printf '%s' "$2" | grep -qF -- "$1"; then ok "$3"; else bad "$3"; printf '        | wanted: %s\n' "$1"; fi; }
wantre() { if printf '%s' "$2" | grep -qE -- "$1"; then ok "$3"; else bad "$3"; printf '        | wanted a match for: %s\n' "$1"; fi; }
notwant(){ if printf '%s' "$2" | grep -qF -- "$1"; then bad "$3"; printf '        | did NOT want: %s\n' "$1"; else ok "$3"; fi; }
rc_is()  { if [ "$RC" = "$1" ]; then ok "$2"; else bad "$2 (rc=$RC, wanted $1)"; printf '%s\n' "$OUT" | sed 's/^/        | /'; fi; }

# --- the fixtures ---------------------------------------------------------------------------------
# Three small images whose contents differ, a record built FROM them, and the second record. The record
# is generated the way the real generator's OUTPUT is shaped (the table row is the contract, and it is
# the same shape `manifests/halium-boot-candidates.md` uses), not by calling the generator: this harness
# must not depend on a second script staying still.
mkdir -p "$W/dir" "$W/out"
mkfx() { # DIR
  rm -rf "$1"; mkdir -p "$1"
  printf 'image one, some bytes\n'   > "$1/a-one.img"
  printf 'image two, more bytes here\n' > "$1/b-two.img"
  printf 'image three\n'             > "$1/c-three.img"
}
mkrecord() { # DIR OUT [extra-row]
  {
    echo "# a fixture record"
    echo
    echo "Generated by \`gen\` on 2026-01-01T00:00:00Z."
    echo
    echo "| file | bytes | sha256 | result |"
    echo "| --- | ---: | --- | --- |"
    for f in "$1"/*.img; do
      [ -e "$f" ] || continue
      b=$(basename -- "$f"); s=$(stat -c %s -- "$f"); h=$(sha256sum -- "$f" | awk '{print $1}')
      printf '| `%s` | %s | `%s` | - |\n' "$b" "$s" "$h"
    done
    [ -n "${3:-}" ] && printf '%s\n' "$3"
  } > "$2"
}
mksums() { ( cd "$1" && sha256sum -- *.img ) > "$1/SHA256SUMS"; }
reset() {
  mkfx "$W/dir"
  mkrecord "$W/dir" "$W/rec.md"
  mksums "$W/dir"
}

run() { # args...
  env -u ZL1_CANDIDATE_MANIFEST -u ZL1_CANDIDATE_DIR \
    "$BASH_BIN" "$SRC" "$@" > "$W/out/last.txt" 2>&1
  RC=$?
  OUT=$(cat "$W/out/last.txt")
}
# The common case: the fixture record and the fixture directory.
r() { run --manifest "$W/rec.md" --dir "$W/dir"; }
rq() { run --manifest "$W/rec.md" --dir "$W/dir" --quick; }

echo "zl1 artifact manifest -- offline self-test"
echo "  subject: $SRC"
echo

# ==================================================================================================
echo "== 1. its own manual, and its arguments =="
# ==================================================================================================
run --help; RC=$?
rc_is 0 "--help exits 0"
want 'the tracked record of the candidate images' "$OUT" "and prints this script's own header"
want 'IN SYNC'      "$OUT" "including the verdicts it can reach"
want 'Generated by' "$OUT" "and the exclusion it makes, by name"
want 'NEVER does'   "$OUT" "and what it never does"
run --nonsense; rc_is 2 "an unknown argument is refused"
run --dir; if [ "$RC" != 0 ] && printf '%s' "$OUT" | grep -qF -- '--dir needs a path'; then
  ok "an argument missing its value is refused, and the flag is named"
else bad "an argument with no value was not refused by name (rc=$RC)"; fi

# ==================================================================================================
echo
echo "== 2. the refusals that come before any comparison =="
# ==================================================================================================
reset
run --manifest "$W/no-such-record.md" --dir "$W/dir"; rc_is 2 "a missing record is refused"
want 'REFUSED' "$OUT" "with REFUSED, not a verdict"
notwant 'IN SYNC' "$OUT" "and it does NOT report agreement with a record it never read"
run --manifest "$W/rec.md" --dir "$W/no-such-dir"; rc_is 2 "a missing directory is refused"
# The sentence that matters: 'I could not look' must never be printed as 'it agrees'.
want 'must not be printed as' "$OUT" "and the reason says why the two are not the same answer"

# ==================================================================================================
echo
echo "== 3. in sync, and the exclusion that makes that possible =="
# ==================================================================================================
reset
r; rc_is 0 "a record built from the directory is IN SYNC"
want '== verdict: IN SYNC' "$OUT" "with the verdict named"
want 'rows in the table: 3' "$OUT" "and the row count it actually compared, so an extractor matching nothing cannot pass"
want 'verified by size AND sha256: 3 rows' "$OUT" "and how many were verified, and by what"
want 'no .img on disk is missing from the record' "$OUT" "and the other direction was read too"
want 'the two records agree on every name they share' "$OUT" "and SHA256SUMS was checked, not assumed"
want 'NOT compared' "$OUT" "and the timestamp line is excluded, by name"

# The fixture's own record carries 2026-01-01. Regenerate the record at a DIFFERENT time and the
# comparison must not move: that line is designed to change, and a check that fails on every run is one
# nobody reads.
sed 's/on 2026-01-01T00:00:00Z\./on 2027-12-31T23:59:59Z./' "$W/rec.md" > "$W/rec-time.md"
run --manifest "$W/rec-time.md" --dir "$W/dir"; rc_is 0 "a different 'generated on' line is NOT drift"
want '== verdict: IN SYNC' "$OUT" "and the verdict stays IN SYNC"

# ==================================================================================================
echo
echo "== 4. every mutation of the disk moves the verdict, and names what moved =="
# ==================================================================================================
# (a) SAME SIZE, DIFFERENT BYTES. This is the case the whole instrument exists for -- an in-place
# rebuild keeps the filename and the size -- and it is the case --quick cannot see.
reset
printf 'image one, SOME bytes\n' > "$W/dir/a-one.img"
r; rc_is 1 "an image edited in place (same size, different bytes) is DRIFTED"
want '== verdict: DRIFTED' "$OUT" "with the verdict named"
want 'DRIFTED   a-one.img' "$OUT" "and the file NAMED, not just a count"
want 'same filename, same size, different bytes' "$OUT" "and the shape of the event it just caught"
rq; rc_is 0 "--quick on the SAME mutation does not see it"
want 'IN SYNC (SIZES ONLY)' "$OUT" "and says which weaker verdict it is"
want 'cannot see an edit that kept the size' "$OUT" "and says out loud what it cannot see"

# (b) a size change
reset
printf 'image three\nand more\n' > "$W/dir/c-three.img"
r; rc_is 1 "an image that grew is DRIFTED"
want 'DRIFTED   c-three.img -- size: record' "$OUT" "and the size mismatch is named as a size mismatch"

# (c) a file the record has and the directory does not
reset
rm -f "$W/dir/b-two.img"
r; rc_is 1 "a file the record has and the disk does not is MISSING"
want 'MISSING   b-two.img' "$OUT" "and it is named"

# (d) the other direction: a real image the record is silent about. This is how a reading gets
# attributed to the wrong file -- nothing else in the tree would notice.
reset
printf 'a brand new build\n' > "$W/dir/d-four.img"
r; rc_is 1 "an image the record does not have is EXTRA"
want 'EXTRA     d-four.img' "$OUT" "and it is named"

# (e) a row the parser cannot read. It must be counted and reported, and it must NOT be counted as
# checked -- a skipped row that is not reported makes the verdict a statement about less than it implies.
reset
sed 's/| `a-one.img` | \([0-9]*\) | `[0-9a-f]*` |/| `a-one.img` | \1 | not-a-hash |/' "$W/rec.md" > "$W/rec-bad.md"
run --manifest "$W/rec-bad.md" --dir "$W/dir"; rc_is 1 "a row this parser cannot read makes the verdict DRIFTED, not a pass"
want 'will NOT be counted as checked' "$OUT" "and the row is named as unread"
want 'unreadable rows: 1' "$OUT" "and counted, so the number checked is honest"

# (f) an EMPTY table. There is nothing to compare against, so there is no reading to give -- and the
# tempting alternative ('no drift found') is a pass on an empty set.
reset
{ echo "# a fixture record"; echo; echo "Generated by \`gen\` on 2026-01-01T00:00:00Z."; echo; } > "$W/rec-empty.md"
run --manifest "$W/rec-empty.md" --dir "$W/dir"; rc_is 3 "a record with no table rows is UNREADABLE"
want '== verdict: UNREADABLE' "$OUT" "with the verdict named"
notwant 'IN SYNC' "$OUT" "and it does NOT report a pass"
want 'a pass on an empty set' "$OUT" "and it names the empty set it was about to pass on"

# (g) the two records disagreeing with each other.
reset
( cd "$W/dir" && sha256sum -- *.img | sed 's/^0*0*/f/' ) > "$W/dir/SHA256SUMS"
r; rc_is 1 "SHA256SUMS disagreeing with the record is DRIFTED"
want 'DISAGREE   a-one.img' "$OUT" "and the disagreement is named per file"
# A name that only ONE of the two records has: they disagree about what EXISTS, not just about bytes.
reset
( cd "$W/dir" && sha256sum -- *.img; printf '%064d  e-five.img\n' 0 | tr '0' 'a' ) > "$W/dir/SHA256SUMS"
r; rc_is 1 "a name in SHA256SUMS that the record does not have is DRIFTED"
want 'ONLY HERE  e-five.img' "$OUT" "and it is named as a disagreement about what exists"

# (h) no SHA256SUMS at all: reported, and NOT counted as a pass.
reset
rm -f "$W/dir/SHA256SUMS"
r; rc_is 0 "a missing SHA256SUMS is NOT a failure"
want 'NOT a failure, and NOT checked' "$OUT" "and it says both halves of that"

# (i) a non-.img file in the directory is not the record's business -- the generator emits *.img only.
reset
printf 'notes\n' > "$W/dir/README.txt"
r; rc_is 0 "a non-.img file in the directory is not EXTRA"
notwant 'EXTRA' "$OUT" "and it is not reported as unaccounted for"

# ==================================================================================================
echo
echo "== 5. it is READ-ONLY, and has no device code path at all =="
# ==================================================================================================
# The subject's claim is that it WRITES NOTHING. Static, over the shipped file: no shell redirection
# onto a path, no rm/mv/touch/mkdir, no dd, no in-place editor. Prose is allowed to name these (it does,
# to say what it never does), so what is checked is that every occurrence is a comment or a printed
# string -- a grep for a defect's shape also matches the sentence forbidding it.
for pat in 'rm -' 'rm -f' 'mv ' 'touch ' 'dd if=' 'dd of=' 'truncate' 'sha256sum >' '>' ; do
  case "$pat" in
  '>')
    # A bare '>' is everywhere in the prose (arrow lines); what must not exist is a redirect to a file.
    n=$(grep -n -- '>>\?[[:space:]]*[^ &|]' "$SRC" | grep -vE ':[[:space:]]*#|say "|2>&1|/dev/null|>&' | grep -c .)
    if [ "$n" = 0 ]; then ok "no shell redirection to a path anywhere in the shipped file"
    else bad "$n redirect(s) to a path -- this instrument claims to write nothing"; fi
    continue ;;
  esac
  tot=$(grep -c -- "$pat" "$SRC")
  code=$(grep -n -- "$pat" "$SRC" | grep -vE ':[[:space:]]*#|say "|echo "' | grep -c .)
  if [ "$tot" = 0 ]; then ok "the shipped script never mentions '$pat'"
  elif [ "$code" = 0 ]; then ok "every mention of '$pat' ($tot) is prose or a comment, and none is a command"
  else bad "'$pat' appears $code time(s) OUTSIDE a comment or a printed string"; fi
done
# It must not have a device code path. Nothing here needs a phone, so the names must not appear at all.
for pat in fastboot adb ssh QFIL fh_loader QSaharaServer; do
  notwant "$pat" "$(cat "$SRC")" "the shipped script does not name '$pat' at all, so it cannot have a device path"
done
want 'sha256sum --' "$(cat "$SRC")" "and it opens images only to hash them"

# ==================================================================================================
echo
echo "== 6. this harness's own citation =="
# ==================================================================================================
HEALTH="$HERE/zl1-health-check.sh"
if [ -r "$HEALTH" ]; then
  match=$(tr '\n' ' ' < "$HEALTH" | grep -oE 'zl1-artifact-manifest-selftest\.sh[^0-9]*[0-9]+ checks' | sed -n 1p)
  cited=$(printf '%s\n' "$match" | sed -n 's/.*[^0-9]\([0-9][0-9]*\) checks$/\1/p')
  total=$(( PASS + FAIL + 1 ))
  if [ -z "$cited" ]; then
    bad "the health check no longer cites this harness's count -- either the citation is gone or its wording changed"
  elif [ "$cited" = "$total" ]; then
    ok "the health check cites $cited checks, and this run has exactly that many"
  else
    bad "the health check cites $cited checks, but this harness has $total -- fix host/zl1-health-check.sh"
  fi
else
  bad "cannot read $HEALTH -- its citations are unchecked"
fi

echo
if [ "$KEEP" = 1 ]; then echo "kept: $W"; else rm -rf "$W"; fi
printf 'pass=%s fail=%s skip=%s\n' "$PASS" "$FAIL" "$SKIP"
[ "$FAIL" = 0 ] || exit 1
exit 0
